### **Assignemtn No 1: Data Wrangling, I**
Perform the following operations using Python on any open source dataset (e.g., data.csv)


## **1. Import all the required Python Libraries.**

Why do we need pandas, why not our excel? 


*   **Advantage**


> quickly analyse data & gives you insight

> need not to be a programmer

*   **Disadvantage**


> Can not handle large amount of data

> it may crashes while loading a data

> Missing value, cleanind data involves lots of process

*   Pandas developed for data analysis
*   support Multiple file format

*   Time series analysis
*   One Script can be used for similar operation again & again


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
#so that we can view the graphs inside the notebook

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


**Fundamental Data Types in Pandas**


1.   Series---- 1 D array with corresponding index
2.   Data Frame ---- n D array



In [ ]:
s1 = pd.Series(range(1,10,1))

In [ ]:
s1

In [ ]:
s3 = pd.Series({1:21, 2:13,3:45})

In [ ]:
s3

In [ ]:
s2 = pd.Series([1, 2, 3, 4], index=['p', 'q', 'r','s'], name='one')

In [ ]:
s2

In [ ]:
df1 = pd.DataFrame(s2)
df1

##2.Locate an open source data from the web (e.g. https://www.kaggle.com). Provide a clear description of the data and its source (i.e., URL of the web site).


## 3.Load the Dataset into pandas data frame

Real power- Import from different formats
http://pandas.pydata.org/pandas-docs/version/0.20/io.html 

In [ ]:
df2 = pd.read_csv("/content/sample_data/california_housing_test.csv") 
#dataframe_name = pd.read_<format>(filename)

In [ ]:
df2.head(10)

In [ ]:
df2.tail(3)

In [ ]:
df2['median_house_value_new']=df2['median_house_value']+111

In [ ]:
df2.tail(3)

In [ ]:
# write
# <dataframe's name>.to_<file_format>(<file_name>)

In [ ]:
df2.to_json('data1.json')

In [ ]:
#If our age dataset is an year old
#df[age_now]= df[age]+1 
df[salary_increment]=df[salary]+5000

In [ ]:
df1['value'] = df1['num']*2
# internally for each value in column num perform each_value*2 and save it as the corresponding
# result in the value column
df1

In [ ]:
len(df1['num'])

In [ ]:
df1['num'].count()

In [ ]:
df1['num'].mean()

In [ ]:
df1['num'].sum()

In [ ]:
df1['num'].median()

In [ ]:
df1['num'].std()

In [ ]:
df1['num'].min()

In [ ]:
df1['num'].max()

In [ ]:
df1['num'].describe()

In [ ]:
df1['num'].cumsum()

In [ ]:
# When you give the whole dataframe, then all numerical columns will be analysis 
df1.mean()

In [ ]:
df1.describe()

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv") 

In [ ]:
df.describe()

In [ ]:
df.columns

In [ ]:
df['longitude']

In [ ]:
df.longitude

In [ ]:
df.iloc[:,1:3]

## 4.Data Preprocessing: 
check for missing values in the data using pandas , describe() function to get some initial statistics. Filling missing values using fillna(), replace() and interpolate()

In [ ]:
# importing pandas as pd
import pandas as pd

# making data frame from csv file 
data = pd.read_csv("employees.csv")

data.head(10)

In [ ]:
data.describe()

In [ ]:
data.isnull()

In [ ]:
data.notnull()

In [ ]:
data.isnull().sum()

### Filling a null values using fillna() 

In [ ]:
# filling a null values using fillna() 
data["Gender"].fillna("No Gender", inplace = True) 

In [ ]:
data.isnull().sum()

In [ ]:
# will replace  Nan value in dataframe with value -99  
import numpy as np
data.replace(to_replace = np.nan, value = -99) 

In [ ]:
# filling a missing value with previous ones  
data.fillna(method ='pad')

In [ ]:
data['Salary'].fillna(int(df['Salary'].mean()), inplace=True)

### Dropping missing values using dropna()

In [ ]:
data.dropna(axis=1)

In [ ]:

# importing pandas as pd
import pandas as pd
  
# Creating the dataframe 
df = pd.DataFrame({"A":[12, 4, 5, None, 1],
                   "B":[None, 2, 54, 3, None],
                   "C":[20, 16, None, 3, 8],
                   "D":[14, 3, None, None, 6]})
  
# Print the dataframe
df

Syntax: DataFrame.interpolate(method=’linear’, axis=0, limit=None, inplace=False, limit_direction=’forward’, limit_area=None, downcast=None, **kwargs)

Parameters :
method : {‘linear’, ‘time’, ‘index’, ‘values’, ‘nearest’, ‘zero’, ‘slinear’, ‘quadratic’, ‘cubic’, ‘barycentric’, ‘krogh’, ‘polynomial’, ‘spline’, ‘piecewise_polynomial’, ‘from_derivatives’, ‘pchip’, ‘akima’}

In [ ]:
df.interpolate(method ='linear', limit_direction ='forward')

# 5.Data Formatting and Data Normalization

## Data Formatting

In [ ]:
#remove white space everywhere
text="today is Monday"
#df['Col Name'] = df['Col Name'].str.replace(‘ ‘, ‘’)
text.replace(' ','')

In [ ]:
text=' Today'
text.lstrip()

In [ ]:
text='Today '
text.rstrip()

In [ ]:
text=' Today '
text.strip()

In [ ]:
ta 

## Data Normalization

**Scaling or Feature Scaling** is the process of changinng the scale of certain features to a common one. This is typically achieved through normalization and standardization.

**Normalization** is the process of scaling data into a range of [0, 1]. It's more useful and common for regression tasks.

x′ =x−xmin / xmax − xmin

**Standardization** is the process of scaling data so that they have a mean value of 0 and a standard deviation of 1. It's more useful and common for classification tasks.

x′=x−μ / σ
Where μ is mean and σ is standard deviation



In [ ]:
import pandas
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler

# data values
X = [ [110, 200], [120, 800], [310, 400], [140, 900], [510, 200], [653, 400] ,[310, 880] ]

# transofrm data
scaler = MinMaxScaler(feature_range=(0,5))
rescaledX = scaler.fit_transform(X)

In [ ]:
X

In [ ]:
rescaledX

### **StandardScaler**

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas
import numpy

# data values
X = [ [110, 200], [120, 800], [310, 400], [140, 900], [510, 200], [653, 400] ,[310, 880] ]

# scaler
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

In [ ]:
rescaledX

array([[-1.02004521, -1.17792918],
       [-0.96841602,  0.90076937],
       [ 0.01253852, -0.48502966],
       [-0.86515765,  1.24721913],
       [ 1.04512224, -1.17792918],
       [ 1.78341961, -0.48502966],
       [ 0.01253852,  1.17792918]])

### Normalize data

In [ ]:
from sklearn.preprocessing import Normalizer
import pandas
import numpy

# data values
X = [ [110, 200], [120, 800], [310, 400], [140, 900], [510, 200], [653, 400] ,[310, 880] ]

# normalize values
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)

In [ ]:
normalizedX

array([[0.48191875, 0.87621591],
       [0.14834045, 0.98893635],
       [0.61257167, 0.79041505],
       [0.15370701, 0.98811647],
       [0.9309732 , 0.36508753],
       [0.8527326 , 0.52234769],
       [0.33225942, 0.94318804]])

### Binary Data Transformation

In [ ]:
from sklearn.preprocessing import Binarizer
import pandas
import numpy

# data values
X = [ [501, 200], [120, 800], [310, 400], [140, 900], [510, 200], [653, 400] ,[310, 880] ]

# binarize data
binarizer = Binarizer(threshold=500).fit(X)
binaryX = binarizer.transform(X)

In [ ]:
binaryX

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1]])

# 6.Turn categorical variables into quantitative variables in Python.

In [ ]:
import pandas as pd
import numpy as np
# Read in the CSV file and convert "?" to NaN
headers = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"]
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data",header=None, names=headers, na_values="?" )
df.head()

In [ ]:
df.dtypes

In [ ]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

In [ ]:
obj_df[obj_df.isnull().any(axis=1)]

In [ ]:
obj_df["num_doors"].value_counts()

four    114
two      89
Name: num_doors, dtype: int64

In [ ]:
obj_df = obj_df.fillna({"num_doors": "four"})

In [ ]:
obj_df[obj_df.isnull().any(axis=1)]

### Approach #1 - Find and Replace
https://pbpython.com/categorical-encoding.html



In [ ]:
obj_df["num_cylinders"].value_counts()

In [ ]:
cleanup_nums = {"num_doors":     {"four": 4, "two": 2},
                "num_cylinders": {"four": 4, "six": 6, "five": 5, "eight": 8,
                                  "two": 2, "twelve": 12, "three":3 }}

In [ ]:
obj_df = obj_df.replace(cleanup_nums)
obj_df.head()

In [ ]:
obj_df.dtypes

### Approach #2 - Label Encoding

In [ ]:
obj_df["body_style"].value_counts()

In [ ]:
obj_df["body_style"] = obj_df["body_style"].astype('category')
obj_df.dtypes

In [ ]:
obj_df["body_style_cat"] = obj_df["body_style"].cat.codes
obj_df.head()

### Approach #3 - One Hot Encoding

In [ ]:
pd.get_dummies(obj_df, columns=["drive_wheels"]).head()

### Approach #4 - Scikit-Learn: OrdinalEncoder and OneHotEncoder

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder()
obj_df["make_code"] = ord_enc.fit_transform(obj_df[["make"]])
obj_df[["make", "make_code"]].head(11)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

oe_style = OneHotEncoder()
oe_results = oe_style.fit_transform(obj_df[["body_style"]])
pd.DataFrame(oe_results.toarray(), columns=oe_style.categories_).head()

In [ ]:
obj_df = obj_df.join(pd.DataFrame(oe_results.toarray(), columns=oe_style.categories_))

In [ ]:
obj_df.head()